[package]
name = "counting-bloom-filter"
version = "0.1.0"
authors = ["Janis Goldschmidt <github@aberrat.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.21.0"
fasthash = "0.4.0"
